export const SET_PROFILE = "SET_PROFILE"
export const SET_TOKEN = "SET_TOKEN"
export const SET_IS_AUTH = "SET_IS_AUTH"
export const SET_RESET = "SET_RESET"
export const LEFTBAR = "LEFTBAR"
export const MENUBAR = "MENUBAR"
export const SOCKET = "SOCKET"